### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
@mundschenk-at Found few misspellings.

https://github.com/crate-ci/typos

### CODE REVIEW

**Comment by mundschenk-at** [comment]
Sorry for the delay in doing anything with this, @szepeviktor. Could you please rebase the PR?

**Comment by mundschenk-at** [comment]
(Alternatively, I can just fix the typos locally, I've now installed the `typos` crate.)

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by szepeviktor** [comment]
> I've now installed the `typos` crate.

So you can discover further typos, e.g. "overrdies"

**Pull request merged**
