### PR TITLE
Leaving deps alone in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
...except on unsupported PHP versions

### CODE REVIEW

**Comment by szepeviktor** [comment]
💣💣 https://github.com/sirbrillig/phpcs-import-detection/issues/44 💣💣

**Comment by mundschenk-at** [comment]
> 💣💣 [sirbrillig/phpcs-import-detection#44](https://github.com/sirbrillig/phpcs-import-detection/issues/44) 💣💣

Among other things, yes 😅

**Comment by szepeviktor** [comment]
Success!!

**Comment by szepeviktor** [comment]
kép

**Pull request closed without merging**
