### PR TITLE
Use boolean operations in maybe_upgrade_schema

### PR DESCRIPTION
**Pull request by szepeviktor**
⚠️ I am not sure in this ❗

### CODE REVIEW

**Comment by mundschenk-at** [comment]
Thank you, but there's reason for the long-winded way this method is written – it is supposed to be extensible and readable even when there are multiple versions with schema changes.

**Comment by mundschenk-at** [comment]
To make things "c&p" proof, I intensionally added the somewhat superfluous `|| $result` in the first line of the `if` statement, so that when someone (me, probably) copies the entire `if`, things still work.

**Comment by szepeviktor** [comment]
I see. Developing an application in WordPress is quite hard, so hard that it will never be an application 😿 
No 6 on this list https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/PHP-development.md#parts-of-an-application

**Comment by szepeviktor** [comment]
Keep up the work!

Meanwhile I add get_comment support to phpstan-wordpress...

**Comment by szepeviktor** [comment]
BTW this is how to make sure only boolean are in `if()`: https://github.com/phpstan/phpstan-strict-rules/blob/70b84f65f2b55427785c470cf8c2cbea5470e3e2/rules.neon#L13-L19

**Pull request closed without merging**
